##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions
## are met:
##  * Redistributions of source code must retain the above copyright
##    notice, this list of conditions and the following disclaimer in the
##    documentation and/or other materials provided with the distribution.
##  * Neither the name of NVIDIA CORPORATION nor the names of its
##    contributors may be used to endorse or promote products derived
##    from this software without specific prior written permission.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
## EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
## IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
## PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
## CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
## EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
## PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
## PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
## OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
## (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
## OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##
## Copyright (c) 2018-2019 NVIDIA Corporation. All rights reserved.

SET(EMSCRIPTEN_USE_ASSERTIONS "1")
SET(EMSCRIPTEN_BASE_OPTIONS "--bind -s MODULARIZE=1 -s EXPORT_NAME=NVCLOTH -s ALLOW_MEMORY_GROWTH=1")


SET(LL_SOURCE_DIR ${PROJECT_ROOT_DIR}/src/)

SET(NVCLOTH_WEB_BINDINGS_INCLUDES
        ${NVTOOLSEXT_INCLUDE_DIRS}
        )

SET(NVCLOTH_WEB_BINDINGS_OBJECT_FILES
        $<TARGET_OBJECTS:NvCloth>
        )

SET(NVCLOTH_WEB_BINDINGS_SRC_FILES)

SET(NVCLOTH_WEB_BINDINGS_LIBTYPE STATIC)
SET(PXNVCLOTH_LIBTYPE_DEFS
        PX_NVCLOTH_STATIC_LIB;
        )

SET(NVCLOTH_WEB_BINDINGS_COMPILE_DEFS
        # Common to all configurations
        ${NVCLOTH_EMSCRIPTEN_COMPILE_DEFS};${PXNVCLOTH_LIBTYPE_DEFS};${NVCLOTH_GPU_SHARED_LIB_NAME_DEF};${PXNVCLOTH_GPU_DEFS}

        $<$<CONFIG:debug>:${NVCLOTH_EMSCRIPTEN_DEBUG_COMPILE_DEFS};>
        $<$<CONFIG:checked>:${NVCLOTH_EMSCRIPTEN_CHECKED_COMPILE_DEFS};>
        $<$<CONFIG:profile>:${NVCLOTH_EMSCRIPTEN_PROFILE_COMPILE_DEFS};>
        $<$<CONFIG:release>:${NVCLOTH_EMSCRIPTEN_RELEASE_COMPILE_DEFS};>
        )

SET(NVCLOTH_WEB_BINDINGS_LINK_FLAGS " ")
SET(NVCLOTH_WEB_BINDINGS_LINK_FLAGS_DEBUG " ")
SET(NVCLOTH_WEB_BINDINGS_LINK_FLAGS_CHECKED " ")
SET(NVCLOTH_WEB_BINDINGS_LINK_FLAGS_PROFILE " ")
SET(NVCLOTH_WEB_BINDINGS_LINK_FLAGS_RELEASE " ")

SET(NVCLOTH_WEB_BINDINGS_LINKED_LIBS dl)

SET(CMAKE_STATIC_LIBRARY_SUFFIX ".bc")

SET(NVCLOTH_WEB_BINDINGS_SOURCE
        ${LL_SOURCE_DIR}/PxWebBindings.cpp
        )
SOURCE_GROUP(src FILES ${NVCLOTH_WEB_BINDINGS_SOURCE})

ADD_EXECUTABLE(NvClothWebBindings ${NVCLOTH_WEB_BINDINGS_SOURCE}
        )

TARGET_COMPILE_DEFINITIONS(NvClothWebBindings
        PRIVATE ${NVCLOTH_WEB_BINDINGS_COMPILE_DEFS}
        )

SET_TARGET_PROPERTIES(NvClothWebBindings PROPERTIES
        LINK_FLAGS "${EMSCRIPTEN_BASE_OPTIONS} -s ASSERTIONS=${EMSCRIPTEN_USE_ASSERTIONS}"
        )

TARGET_LINK_LIBRARIES(NvClothWebBindings
        PUBLIC NvCloth
        )

TARGET_INCLUDE_DIRECTORIES(NvClothWebBindings
        PRIVATE ${NVCLOTH_PLATFORM_INCLUDES}

        PRIVATE ${PXSHARED_ROOT_DIR}/include
        PRIVATE ${PXSHARED_ROOT_DIR}/src/foundation/include

        PRIVATE ${PROJECT_ROOT_DIR}/include
        PRIVATE ${PROJECT_ROOT_DIR}/extensions/include
        PRIVATE ${PROJECT_ROOT_DIR}/src
        PRIVATE ${PROJECT_ROOT_DIR}/extensions/src
        )

# name the output library 'nvcloth' as this is really a union of all of js-bound NvCloth
set_target_properties(NvClothWebBindings PROPERTIES OUTPUT_NAME "nvcloth.${CMAKE_BUILD_TYPE}")
